### ISSUE TITLE
Not logging into Airtable

### ISSUE THREAD

**Issue by aivantg** [cape-io/airtable-schema#1]
I've been using this package for a while, and it was working great. But very recently, it seems like it can't log into the airtable website properly for some reason. Any ideas on what airtable might have changed? 

Thanks! Love this repo, super clever idea :)

**Comment by vikramrojo** [comment]
having the same problem :(

**Comment by aivantg** [comment]
@atav1k I've made a PR to fix! Take a look at the code if you're interested in the fix!

**Comment by vikramrojo** [comment]
@aivantg the fs-extra pkg was lost in the shuffle btw.
